"""add event call_id and run metadata

Revision ID: 45824106d57f
Revises: f460665ddc97
Create Date: 2026-09-18 22:40:22.255773+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '45824106d57f'
down_revision: str | None = 'f460665ddc97'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('call_id', sa.String(length=255), nullable=True))
    op.create_index('ix_events_run_id_call_id', 'events', ['run_id', 'call_id'], unique=False)
    op.add_column('runs', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'metadata')
    op.drop_index('ix_events_run_id_call_id', table_name='events')
    op.drop_column('events', 'call_id')
    # ### end Alembic commands ###
