"""create comparisons

Revision ID: 954212f03eea
Revises: e782b8e9cfa1
Create Date: 2026-09-23 10:44:44.597567+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '954212f03eea'
down_revision: str | None = 'e782b8e9cfa1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparisons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('replay_run_id', sa.UUID(), nullable=False),
    sa.Column('recording_run_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verdict IN ('pass', 'fail')", name=op.f('ck_comparisons_verdict_valid')),
    sa.ForeignKeyConstraint(['recording_run_id'], ['runs.id'], name=op.f('fk_comparisons_recording_run_id_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replay_run_id'], ['runs.id'], name=op.f('fk_comparisons_replay_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comparisons')),
    sa.UniqueConstraint('replay_run_id', name=op.f('uq_comparisons_replay_run_id'))
    )
    op.create_index(op.f('ix_comparisons_recording_run_id'), 'comparisons', ['recording_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comparisons_recording_run_id'), table_name='comparisons')
    op.drop_table('comparisons')
    # ### end Alembic commands ###
