"""add runs replay_of_run_id

Revision ID: e782b8e9cfa1
Revises: 45824106d57f
Create Date: 2026-09-22 20:41:32.178135+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e782b8e9cfa1'
down_revision: str | None = '45824106d57f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('replay_of_run_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_runs_replay_of_run_id'), 'runs', ['replay_of_run_id'], unique=False)
    op.create_foreign_key(op.f('fk_runs_replay_of_run_id_runs'), 'runs', 'runs', ['replay_of_run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_runs_replay_of_run_id_runs'), 'runs', type_='foreignkey')
    op.drop_index(op.f('ix_runs_replay_of_run_id'), table_name='runs')
    op.drop_column('runs', 'replay_of_run_id')
    # ### end Alembic commands ###
